/*-------------------------------------------------------------------------
 *
 * ag_edge_d.h
 *    Macro definitions for ag_edge
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef AG_EDGE_D_H
#define AG_EDGE_D_H

#define EdgeRelationId 7020
#define EdgeRelation_Rowtype_Id 7022

#define Anum_ag_edge_id 1
#define Anum_ag_edge_start 2
#define Anum_ag_edge_end 3
#define Anum_ag_edge_properties 4
#define Anum_ag_edge_tid 5

#define Natts_ag_edge 5


#endif							/* AG_EDGE_D_H */
