/*-------------------------------------------------------------------------
 *
 * ag_graphpath_d.h
 *    Macro definitions for ag_graphpath
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef AG_GRAPHPATH_D_H
#define AG_GRAPHPATH_D_H

#define GraphPathRelationId 7030
#define GraphPathRelation_Rowtype_Id 7032

#define Anum_ag_graphpath_vertices 1
#define Anum_ag_graphpath_edges 2

#define Natts_ag_graphpath 2


#endif							/* AG_GRAPHPATH_D_H */
