/*-------------------------------------------------------------------------
 *
 * ag_graph_d.h
 *    Macro definitions for ag_graph
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef AG_GRAPH_D_H
#define AG_GRAPH_D_H

#define GraphRelationId 7040
#define GraphOidIndexId 7041
#define GraphNameIndexId 7042

#define Anum_ag_graph_oid 1
#define Anum_ag_graph_graphname 2
#define Anum_ag_graph_nspid 3

#define Natts_ag_graph 3


#endif							/* AG_GRAPH_D_H */
