/*-------------------------------------------------------------------------
 *
 * ag_graphmeta_d.h
 *    Macro definitions for ag_graphmeta
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef AG_GRAPHMETA_D_H
#define AG_GRAPHMETA_D_H

#define GraphMetaRelationId 7055
#define GraphMetaFullIndexId 7056
#define GraphMetaStartIndexId 7057
#define GraphMetaEndIndexId 7058

#define Anum_ag_graphmeta_graph 1
#define Anum_ag_graphmeta_edge 2
#define Anum_ag_graphmeta_start 3
#define Anum_ag_graphmeta_end 4
#define Anum_ag_graphmeta_edgecount 5

#define Natts_ag_graphmeta 5


#endif							/* AG_GRAPHMETA_D_H */
