/*-------------------------------------------------------------------------
 *
 * ag_label_d.h
 *    Macro definitions for ag_label
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef AG_LABEL_D_H
#define AG_LABEL_D_H

#define LabelRelationId 7045
#define LabelOidIndexId 7046
#define LabelNameGraphIndexId 7047
#define LabelGraphLabelIndexId 7048
#define LabelRelidIndexId 7049

#define Anum_ag_label_oid 1
#define Anum_ag_label_labname 2
#define Anum_ag_label_graphid 3
#define Anum_ag_label_labid 4
#define Anum_ag_label_relid 5
#define Anum_ag_label_labkind 6

#define Natts_ag_label 6


#endif							/* AG_LABEL_D_H */
