/*-------------------------------------------------------------------------
 *
 * ag_vertex_d.h
 *    Macro definitions for ag_vertex
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef AG_VERTEX_D_H
#define AG_VERTEX_D_H

#define VertexRelationId 7010
#define VertexRelation_Rowtype_Id 7012

#define Anum_ag_vertex_id 1
#define Anum_ag_vertex_properties 2
#define Anum_ag_vertex_tid 3

#define Natts_ag_vertex 3


#endif							/* AG_VERTEX_D_H */
